### ISSUE TITLE
Import tickets by scanning barcode

### ISSUE THREAD

**Issue by schildbach** [ligi/PassAndroid#1]
This is a request for enhancement.

Rather than only be able to import passbook files, why not also just scan the barcode of any ticket? For example the Droidcon ticket, there is no passbook for that.

Of course it would be important that the barcodes are displayed in the same format as they were recorded.

**Comment by ligi** [comment]
There is now the feature to create passes and also scan barcodes for these passes

**Comment by schildbach** [comment]
Nice, thanks!
