### ISSUE TITLE
Show more data in lists

### ISSUE THREAD

**Issue by wmertens** [ligi/PassAndroid#108]
When looking at the list of passes, some important data is not visible, like date, time and the name on the pass.

**Comment by ligi** [comment]
Thanks for the feedback. I cannot show all data in the overview - have to make a cut there - I did it at 2 lines. You know you can see more in condensed mode? Closing this for now as I do not think this would be a good change

**Comment by wmertens** [comment]
Hmm, this is with condensed mode turned on, all I see is that I have a
boarding pass for a certain airport and airline. No dates, times,
passengers, … while there is still a bunch of space available.

Furthermore, I would expect most people not to have a lot of tickets in the
list, so even if the longer items would overflow the screen, they would not
have to scroll far and they would need to do a lot less navigation in
return…

**Comment by ligi** [comment]
perhaps #109 solves your problem a bit - how many passes do you usually have?

**Comment by wmertens** [comment]
So for this trip I have 4 passes in each direction…

**Comment by normanr** [comment]
4 different legs, or 4 people on the same leg? (It could show 'current' leg by default.

**Comment by wmertens** [comment]
Yes, 4 people on the same leg…

>
