### ISSUE TITLE
add FAQ item

### ISSUE THREAD

**Issue by ligi** [ligi/PassAndroid#11]
https://plus.google.com/107859285944394129250/posts/LLpqFCX7yJV

**Comment by guerda** [comment]
I would like to contribute to this project and start with the low hanging fruits (like this translation issue). Can you accept my request to join the transifex team?

I propose to extend the help screen with an FAQ section. This is quite an easy fix and hopefully where the user searches for it. Some questions could be answered there
* How to transfer passes from iOS to Android?
* Why was this app developed? (https://twitter.com/mr_ligi/status/678708731190841346) 
What do you think?

**Comment by ligi** [comment]
Great! Just accepted your request for transifex

**Comment by guerda** [comment]
I added a first version in German, unfortunately I'm not able to change the English one.

**Comment by guerda** [comment]
I needed to add the English version of the FAQ within the source code, as Transifex needs this for the source language. The German one is already updated, as you updated all files from Transifex.
Thanks!
