### ISSUE TITLE
Update to version 3.2.7 in Google Play

### ISSUE THREAD

**Issue by homocomputeris** [ligi/PassAndroid#111]
Could you update Google Play version, please?

**Comment by ligi** [comment]
Not yet - I detected a small bug and am now holding the staged roll-out - will upload a 3.2.8 to beta soon
Is there any specific reason you need 3.2.7 now?

**Comment by homocomputeris** [comment]
Thanks for the explanation.
Nothing specific, just hoped for the 'cutting-edge' :)

**Comment by ligi** [comment]
thanks for the follow-up - join the betatesters if you want to be on the cutting-edge - could use some more betatesters ( especially ones that are able to write issues on github :)
