### ISSUE TITLE
Shortcut creation individual cards

### ISSUE THREAD

**Issue by msix81** [ligi/PassAndroid#112]
When dealing with loyalty cards I want to avoid any more clicks at the cashier than necessary. Currently I have to open PassAndroid (1 click) and manually select the card I want (another click), maybe even enlarge the barcode (yet another click). Idea: Offer PassAndroid when creating a standard Android shortcut on the home screen, and point to a specific card directly; similar to e.g. create a shortcut to text a recipient in your address book directly. Maybe even offer two shortcut options for small an large barcode display.

**Comment by ligi** [comment]
Is a good idea - but I will do this only for Android 6.0+ as this requires a new permission

**Comment by ligi** [comment]
I have this working in a branch now - works fine - thanks for the suggestion. Please join the betatesters as this feature will be available there first

**Comment by msix81** [comment]
Wow, this is great, thanks for the quick response! I am beta tester already and will provide feedback as soon as I have it (yes, am working on a 6.0+ device). Awesome!

**Comment by ligi** [comment]
Did you have a chance to try out the feature - does it need tweaking?

**Comment by msix81** [comment]
Haven't received any beta update yet - did you release it already?

**Comment by msix81** [comment]
I see version 3.2.8 in the beta channel

**Comment by ligi** [comment]
Good that we talked about this ;-) I uploaded to beta but forgot to publish afterwards. Fixed now - should be live soon

**Comment by msix81** [comment]
Got it, thanks.

I cannot create a shortcut via my launcher's  (Apex) default "create shortcut"-functionality. However I can create a shortcut via the PassAndroid burger menu. The selected pass' detail page opens without any errors. 
Unfortunately it does not memorize the barcode size, i.e. I still need to manually enlarge the supermarket's loyalty card's EAN13 for reading at the cashier. Anyway, the shortcut functionality works, thank you!!

**Comment by ligi** [comment]
Created a follow-up ticket for the barcode size - not yet sure about what to do for the Apex laucher though

**Comment by msix81** [comment]
Just tried it with the Google Now launcher: it seems there is no shortcut functionality anymore (I can select only apps, widgets or backgrounds). So maybe this has been discontinued by Google and Apex only supports it for legacy purposes. Never mind.
