### ISSUE TITLE
"Navigate to"- and "Add to Calendar"-icons swapped

### ISSUE THREAD

**Issue by niemalsnever** [ligi/PassAndroid#126]
Hi,
it seems that in v3.3.2 you swapped the icons for the buttons that invoke the "Navigate to"-function and the "Add to Calendar"-function.

Using Android 6.0.1 and PassAndroid 3.3.2
![Screenshot](https://cloud.githubusercontent.com/assets/6272364/21071038/a1b0a810-be94-11e6-87d1-d397da44d261.JPG)

**Comment by ligi** [comment]
Thanks for letting me know - enjoy your #33c3 ;-)
