### ISSUE TITLE
Support Interleaved 2 of 5 (ITF, Interleaved Two of Five) Barcode

### ISSUE THREAD

**Issue by stoll-it** [ligi/PassAndroid#131]
Some cards that can be used for payment use the [Interleaved 2 of 5 (Wikipedia link)](https://en.wikipedia.org/wiki/Interleaved_2_of_5) (ITF) barcode. It would be great if the "Edit BarCode"-Dialog would support the creation of this barcode.

It seems that PassAndroid uses the com.google.zxing.MultiFormatWriter which already supports this format https://zxing.github.io/zxing/apidocs/com/google/zxing/BarcodeFormat.html#ITF

**Comment by ligi** [comment]
Thanks

**Comment by ligi** [comment]
Just released 3.3.5 as beta with this feature

**Comment by stoll-it** [comment]
I tried it with a real barcode in a store and it worked! For others trying the same: While the store's fixed scanner on the counter didn't accept the barcode, the store's handheld scanner did. Thank you! :+1:
