### ISSUE TITLE
Navigate button navigates to the wrong Airport

### ISSUE THREAD

**Issue by tobwiens** [ligi/PassAndroid#133]
Got a lufthansa ticket to fly from bkk airport.

Clicked on navigate and it showed me Dong Muan airport. 

That is especially bad because the navigate button links with the uber app. I would have went to the wrong airport. 

Sorry I didn't check the code and don't know if this project provides the destination coordinates. 

Cheers

**Comment by ligi** [comment]
Thanks for the feedback  - this is really strange - the coordinates are provided by the pass - are you able to send me the ( original pkpass ) file?
