### ISSUE TITLE
Performance improvement suggestion

### ISSUE THREAD

**Issue by struggggle** [ligi/PassAndroid#136]
Dear developers,
I found some potential slow operations of bitmap displaying in PassAndroid. 
When loading images, images come in all shapes and sizes. In many cases they are larger than required for a typical application user interface (UI). Google suggests us to check and resize the image before decoding them. it works like this:
https://developer.android.com/training/displaying-bitmaps/load-bitmap.html

_public static Bitmap decodeSampledBitmapFromResource(Resources res, int resId,
        int reqWidth, int reqHeight) {
    // First decode with inJustDecodeBounds=true to check dimensions
    final BitmapFactory.Options options = new BitmapFactory.Options();
    options.inJustDecodeBounds = true;
    BitmapFactory.decodeResource(res, resId, options);
   // Calculate inSampleSize
    options.inSampleSize = calculateInSampleSize(options, reqWidth, reqHeight);
    // Decode bitmap with inSampleSize set
    options.inJustDecodeBounds = false;
    return BitmapFactory.decodeResource(res, resId, options);
}_

However, in the code below, images are decoded directly without checking and resizing: 
org.ligi.passandroid.ui.UnzipPassController.processFile()
https://github.com/ligi/PassAndroid/blob/master/android/src/main/java/org/ligi/passandroid/ui/UnzipPassController.kt
org.ligi.passandroid.model.pass.PassImpl.getBitmap()
https://github.com/ligi/PassAndroid/blob/master/android/src/main/java/org/ligi/passandroid/model/pass/PassImpl.kt
org.ligi.passandroid.reader.AppleStylePassReader.findBitmap()
https://github.com/ligi/PassAndroid/blob/master/android/src/main/java/org/ligi/passandroid/reader/AppleStylePassReader.kt

Why these methods do not resize images? Are these images of small sizes?

Do you think not perform image resizing will affect PassAndroid's performance? If yes, perhaps checking and resizing the images before decoding them can help make app more smooth in user interaction.

Looking forward to your response and hope I can help improve PassAndroid.
Thanks.

**Comment by ligi** [comment]
Do you have an example pass where these images are large? I do not see any performance problems there yet.

**Comment by struggggle** [comment]
Sorry, I don't have. 
I don't familiar with the source code of PassAndroid, and I just found these parts of the code which I thought they would incur additional performance overhead in some special cases. I think if the size of an image is larger than the size of the UI component that displays it, we can say the image is large. If there exists one image to be displayed is very large, which may cause performance issue.

**Comment by ligi** [comment]
no worries - but I will close this one - please google for:

  "Premature optimization is the root of all evil"

unless I see or measure a problem here I will not optimize this part.
