### ISSUE TITLE
App does not start on the Emulator

### ISSUE THREAD

**Issue by nicola-amatucci** [ligi/PassAndroid#137]
App does not start on the Emulator. I've attached logcat trace.

The problem seems related to Tracedroid Library.

[logcat_emulator-5554_0.txt](https://github.com/ligi/PassAndroid/files/714096/logcat_emulator-5554_0.txt)

Thank you.

**Comment by ligi** [comment]
thanks - but I need more information: which version are you using and where is the build-from

**Comment by nicola-amatucci** [comment]
I've downloaded the APK from FDroid. Version 3.3.5.

I'm using Android SDK Version 23 (Android 6.0), latest platform tools.

https://f-droid.org/repository/browse/?fdfilter=PassAndroid&fdid=org.ligi.passandroid

**Comment by ligi** [comment]
Hm - really strange - I just downloaded and installed 3.3.5 from fdroid on the emu and do not see a problem there - also all the tests run on emulators also - not sure yet what is going on on your side - will have to investigate deeper - some more info can help

**Comment by ligi** [comment]
closing this now - feel free to reopen with more information
