### ISSUE TITLE
Data Matrix

### ISSUE THREAD

**Issue by Aggr094** [ligi/PassAndroid#139]
Could you please support [Data Matrix](https://en.wikipedia.org/wiki/Data_Matrix) as format?

**Comment by ligi** [comment]
Thanks for the feedback - will most likely do this - but need to know about your use-case

**Comment by Aggr094** [comment]
I want to put my Subway pointcard in Passandroid. It uses a Data Matrix as format.

**Comment by ligi** [comment]
thanks! will be implemented soon

**Comment by ligi** [comment]
link #131 ~=

**Comment by ligi** [comment]
3.3.7 contains support for Data-Matrix - will release to beta first - please let me know if it works for you and thanks a lot for the feedback!
