### ISSUE TITLE
Display brightness

### ISSUE THREAD

**Issue by deboerk** [ligi/PassAndroid#14]
Hi,
thanks for your great app! I used it on my last flight and found it to be very useful. I only had one issue: When displaying the QR code in full size the display brightness was to low to scan the code. It would be great if the display was turned to maximum brightness when the QR code is displayed.

Cheers,
deboerk

**Comment by ligi** [comment]
there is now the button to set full brightness - hope it works for you - until then I am closing this issue

**Comment by oliv3r** [comment]
after importing a PNG the auto-brightness works fine when not having it 'selected/maximized'. However maximizing it the brightness is lowered to my current android setting. Also this button seems to be not available in maximized mode on v3.4.6.
