### ISSUE TITLE
Dutch translation not werking?

### ISSUE THREAD

**Issue by theroggy** [ligi/PassAndroid#150]
A few months ago I translated the app in Dutch... but it doesn't appear in Dutch yet when installed... is there still something wrong with the translation or?

**Comment by ligi** [comment]
Thanks for letting me know and translating - will investigate where this is stuck soon

**Comment by ligi** [comment]
Sorry my fuckup - there is a bad char - I got this in once at a bad timing - then forgot about it:

/home/ligi/git/PassbookForAndroid/android/build/intermediates/res/merged/noMapsNoAnalyticsForFDroid/debug/values-nl/values-nl.xml:149: AAPT: Apostrophe not preceded by \ (in 

this is something in the help text - did not yet find where exactly - if you spot it let me know

**Comment by theroggy** [comment]
In the help text there is a sentence like this { "free" zoals "bier" }

Those are apostrophe caracters... might those be the culprits?

**Comment by ligi** [comment]
The ' in the urls have been the problem - replaced with \' - sorry it took so long - thans for the follow-up - will build a new version with this included soon

**Comment by theroggy** [comment]
Odd... The single quotes were in the English  translation, so I thought that couldn't ne the problem.

Anyway... great that it is solved!
Thanks!

**Comment by theroggy** [comment]
*also in the english translation

**Comment by ligi** [comment]
yea but in the english one they have all been escaped. Btw. are you registered as a betatester? Will roll out the version with the dutch translations there first.

**Comment by theroggy** [comment]
Ah... in the ui of transife the I didn't see the escape  characters in english... but now I see them in dutch... 
Anyway... in the future I'll try to think about it.

Yes, I'm a betatester...

**Comment by ligi** [comment]
Yea - this might be a transifex bug - I am kinda looking if I switch at some point - the Web-UI is so confusing and complicated .. Also I am having problems tracking down changes.
Something really integrated in git would be nice. Anyway I will release 3.4.0 to beta soon that contains your translations. Can you please add yourself to the credits?
