### ISSUE TITLE
Update app in Play Store

### ISSUE THREAD

**Issue by simontb** [ligi/PassAndroid#156]
On F-Droid version 3.4.0 is available, however in the Play Store I can only download 3.3.9

**Comment by lnicola** [comment]
Also, the F-Droid signing key changed.

**Comment by ligi** [comment]
@lnicola can you contact fdroid for the changed key? I have no control over this.

@simontb thanks - finally updated on play - 3.4.1 now available there

**Comment by lnicola** [comment]
@ligi Neither do I 😄.
