### ISSUE TITLE
Wrong Date Sorting

### ISSUE THREAD

**Issue by jnsc** [ligi/PassAndroid#157]
My passes are ordered by date ascending :
![screenshot_20170713-112522](https://user-images.githubusercontent.com/1291483/28161647-97163080-67c4-11e7-87fa-82bffe8cb3ed.png)

But the ordering seems wrong, it might be that the first passes date is separated by / and the others by .
![screenshot_20170713-112508](https://user-images.githubusercontent.com/1291483/28161646-97134ec4-67c4-11e7-89f0-dcf6ba8f7b4a.png)

**Comment by jnsc** [comment]
It might even be that dates separated by / are not recognized, as I just realize that the calendar option is missing.

**Comment by ligi** [comment]
Yea - means the first 2 passes do not have a relevantDate field - so it is treated as having no date at all - might be confusing as you see a date - but this is free text - and there I e.g. have no timezone - no real idea on how to deal with this ideally ..

**Comment by jnsc** [comment]
Thanks for you answer, I will try to ask the issuer to correct there passes. He might accept.

**Comment by ligi** [comment]
Great! Thanks!
