### ISSUE TITLE
AirCanada URLs not recognised

### ISSUE THREAD

**Issue by bosth** [ligi/PassAndroid#160]
PassAndroid 3.4.0

AirCanada electronic boarding pass URLs no longer work with PassAndroid. The new format I am seeing in an email from AirCanada is https://mci.aircanada.com/mci/bp/xyz

PassAndroid reports the following supported links:

- m.aircanada.ca
- services.aircanada.com

**Comment by ligi** [comment]
Thanks for bringing this up! Are you able to share such a real link with me? I need to know if only the url-scheme is different or if there is another difference and Ideally verify the code change I made to fix this.

**Comment by bosth** [comment]
Here are two examples (now expired):

https://m.aircanada.com/mci/bp/9Em90Oy6QwIw6tlO9NCaw1bef
https://m.aircanada.com/mci/bp/zQxEKXNsl64U70LTshsBA1bef

**I had the URL format wrong in my initial ticket.** The format is *m.aircanada.com* not *mci.aircanada.com*.

**Comment by ligi** [comment]
Thanks! unfortunately they 404 now - so I cannot really reproduce the fix - you do not have to have that do not 404? You can also send them to me via email if you do not want to share them in this issue.

**Comment by bosth** [comment]
Not sure when I'll get a new link to test - plus it'll only be active for about 24 hours. Happy to test a APK built with the proposed patch if that will help when the time comes.

**Comment by ligi** [comment]
This is a good idea - will try to get a version with this to beta soon - thanks!

**Comment by bosth** [comment]
Will definitely test this as soon as I can. Thanks!

**Comment by ligi** [comment]
Great! This is now included in the latest beta 3.4.1

**Comment by bosth** [comment]
Confirmed that with 3.4.3, the new URLs from AirCanada are recognised. Thank you!

**Comment by ligi** [comment]
Thanks a lot for the confirmation! Have safe flights!!
