### ISSUE TITLE
Make shared passes compatible with iOS wallet

### ISSUE THREAD

**Issue by guerda** [ligi/PassAndroid#161]
I wanted to share a pass with an iOS device but the file types are not compatible. The original pass was a WizzAir boarding pass. After sharing, the file was an espass file and couldn't be imported by iOS wallet. The original file was able to be imported to iOS wallet. 

# Steps to reproduce
1. Import a Pass in PassAndroid
2. Open pass
3. Share pass via any app to an iOS device.
4. Open Pass on iOS devices

# Expected results
Pass is shared as the original file type or a compatible type and successfully  imported to wallet.

# Actual results
A espass file is shared, which iOS cannot open/import to the wallet.

**Comment by ligi** [comment]
Thanks for the feedback - but to be honest I do not care for iOS - also the passbook format should be replaced and not spread further. Also have a lot of other stuff on my plate - so If I would find time I would do other stuff - sorry but I am closing this.
