### ISSUE TITLE
[LowPrio] Launcher Shortcut has Green Android Icon

### ISSUE THREAD

**Issue by symbolisch1234** [ligi/PassAndroid#162]
PassAndroid 3.4.0 (F-Droid) on Sony Xperia Z3C running Lineage 14.1 (Android 7.1.2)

* Open PassAndroid
* Open a Pass
* Tap the ...-Menu Icon, choose "Launcher Shortcut"

Expected Behaviour: A Launcher Shortcut with the PassAndroid Icon or (ideally) an icon matching category/color/icon of the pass is created.

Actual Behaviour: A Launcher Shortcut with a generic green android icon is created.

**Comment by ligi** [comment]
Thanks for the report - just tried to reproduce on one device and I get the PassAndroid Icon for the link. Will have to dig there deeper. Can you make a screenshot by any means?

**Comment by symbolisch1234** [comment]
i create a test pass:
![issue-01](https://user-images.githubusercontent.com/16333258/29791364-ea7089dc-8c3c-11e7-8391-56176f1c0562.png)

this is the launcher created:
![issue-02](https://user-images.githubusercontent.com/16333258/29791371-f1169a24-8c3c-11e7-9c2b-5ef599530263.png)

I can easily reproduce this issue on Sony Xperia M running Lineage 14.1 (Android 7.1.1), also 3.4.0 from F-Droid. So it is not just my single device, but both are running very similar ROMs. I have a Samsung S3 Mini with Stock (Samsung) lying here, and will try once it get it to start (which it doesn't)...

**Comment by symbolisch1234** [comment]
Now on Samsung S4 Mini running Stock (Samsung) Android 4.2.2 - freshly installed PassAndroid 3.4.0 from F-Droid.

LOL, i don't have the option for Launcher shortcut. There is no ...-Menu, instead only a trashcan. The device has a physical "menu"-button, but when i press it, nothing happens. Sorry... :-/

**Comment by symbolisch1234** [comment]
Bug is also present in 3.4.0 on LG GPad 8.3 running Lineage 14.1 (Android 7.1.1). I will try to get my hand on a device not running Lineage.

**Comment by friedger** [comment]
I can confirm this for the trebuchet launcher (on one plus one)

**Comment by symbolisch1234** [comment]
* downloaded ADW Launcher 1.3.6 on the Xperia M (Lin14.1) and it is the same as on trebuchet. 
* on OpenLauncher 0.5.3 there is no icon created whatsoever. there is a shortcut with the name of the pass, and i can tap it, but the icon is a wholly transparent area.

Pretty sure it is not the Trebuchet Launcher.
