### ISSUE TITLE
Test for Visibility of open file

### ISSUE THREAD

**Issue by ligi** [ligi/PassAndroid#164]
https://github.com/ligi/PassAndroid/commit/cf2dff6b1301c416aa595c70e624584b25520496

**Comment by simontb** [comment]
But why is the default visibility set to gone? (https://github.com/ligi/PassAndroid/blob/e02af2ef81cbf13b97e824c0a95f59ccfc5bb894/android/src/main/res/layout/pass_list.xml#L69-L74)

Then make the item visible in the Activity:

    fab_action_open_file.visibility = VISIBLE

**Comment by ligi** [comment]
I think gone is a safe default ..-)

**Comment by simontb** [comment]
But then it should be set to visible in the Activity and the else-block can be deleted, right?

https://github.com/ligi/PassAndroid/blob/e02af2ef81cbf13b97e824c0a95f59ccfc5bb894/android/src/main/java/org/ligi/passandroid/ui/PassListActivity.kt#L204-L210

**Comment by ligi** [comment]
https://github.com/ligi/PassAndroid/commit/cf2dff6b1301c416aa595c70e624584b25520496 is seting it to visible - but you are right - the else block is not needed anymore

**Comment by simontb** [comment]
Is cf2dff6 not in the master branch yet?

**Comment by ligi** [comment]
yea - have not yet merged it in - will do soon
