### ISSUE TITLE
PassAndroid Barcode Scanning only searches for selected code type

### ISSUE THREAD

**Issue by symbolisch1234** [ligi/PassAndroid#172]
I found the Barcode Scanning Feature integrated in PassAndroid just now, so I tried it for the first time. And the User Interface is quite unintuitive. 

I know Barcode Scanner (com.google.zxing.client.android), and (if i understand) Pass Android is using the zxing library. It displays the Barcode Scanner User Interface. However, **the behaviour is different**. While Barcode Scanner scans for all types of codes, PassAndroid only scans for the code which is selected in the radio button below. If you have selected QR code (the default) it will never scan an Aztec code ever. And while you are scanning, the radio buttons are not even visible, so you can not realise your mistake.

The problem is less the behaviour, and more the inconsistency with Barcode Scanner (which user interface it borrows!). It took me nearly an hour to realise this, and only after I tested it with three different devices, and was already writing the bug report.

I know, not everyone is as stupid as me, but if it takes me an hour to figure this out, others might struggle a few minutes, and then give up.

**Comment by Discordanian** [comment]
Oh, I thought the barcode scanner just didn't work.  How am I to know which type of barcode is on the back of a given card?  Do you just end up trying them all?

**Comment by symbolisch1234** [comment]
well, you learn them by heart: http://www.barcodefaq.com/BarcodeMatch/ (or https://en.wikipedia.org/wiki/Barcode#Matrix_.282D.29_barcodes for even more ) 

No, I would download Barcode Scanner (com.google.zxing.client.android) from F-Droid or Google Play, go to settings, and tell it to scan for all codes. That is the easiest way. After some time you learn the characteristics of the most common ones (which are QR, DataMatrix, PDF417 for the 2D-types, and for the 1D-types Code39, Code128, UPC/EAN).

**Comment by woj-tek** [comment]
I think by default it should just scan all (with the underlying library) and then offer user to select type (so user would be able to have same info as displayed on the page/boarding pass). 

BarcodeScanner scans/detects everything automatically just fine.

**Comment by Mannshoch** [comment]
Another Question
After I scanned successfully a Bording pass. How do i get it saved? There is no save button and if I simply press Back the Barcode is not saved.
