### ISSUE TITLE
Not seeing the active tab

### ISSUE THREAD

**Issue by jorrit** [ligi/PassAndroid#184]
I loaded 9 pass files into PassAndroid v3.4.3 on a Samsung Galaxy S7 running android 7.0. After this, they're sorted pn import date and I only see the New tab. According tp the screenahots I should get an Active tab and Trash tab.
![screenshot_20180125-152749](https://user-images.githubusercontent.com/521449/35393365-0bfba208-01e5-11e8-972e-d6cb9db26d78.png)

**Comment by eternaltyro** [comment]
@jorrit  You have to "Swipe" the individual pass right / left; you'll then get an option to create tabs or send the pass to "trash" or "archive".

**Comment by jorrit** [comment]
Thanks
