### ISSUE TITLE
Close navigation drawer on back press

### ISSUE THREAD

**Issue by simontb** [ligi/PassAndroid#191]
Currently pressing back closes the app

**Comment by ligi** [comment]
thanks for the feedback - but I cannot reproduce the problem - already works like this for me:

![closing_nav](https://user-images.githubusercontent.com/111600/38372657-a33a216c-38ef-11e8-88cd-521491b2a271.gif)

**Comment by simontb** [comment]
This is how it looks on Huawei P10 running Android 8.0.0:

![ezgif-2-a3d3904343](https://user-images.githubusercontent.com/6491719/38373127-c85a6460-38f0-11e8-97ee-20e6f6154ca8.gif)

**Comment by ligi** [comment]
Thanks - very strange - what version are you using? The feature came via 1f4ac8bd7bd8dcc516dbdaac4bded59fe04c6767 - perhaps you have a version before?

**Comment by simontb** [comment]
I'm on version 3.4.5 from Google Play. FAB closes on back press.

Maybe I can find out the cause of this behavior on my phone and open a PR.

**Comment by ligi** [comment]
Thanks - that would be great - don't really know what to do here as I cannot reproduce the problem

**Comment by ligi** [comment]
cloesed via eac62d8bd8a239fe2b2e8790020ec58f3a3cceb1 - thanks for the report and fix!
