### ISSUE TITLE
Migrate deprecated dependencies

### ISSUE THREAD

**Issue by irgendwr** [ligi/PassAndroid#224]
It's not possible to upgrade Gradle/AGP to the recent version due to two deprecated dependencies.

- [x] [Backend] Migrate the old appengine plugin to the new one, see https://cloud.google.com/endpoints/docs/frameworks/legacy/v1/java/migrating-android and https://github.com/GoogleCloudPlatform/app-gradle-plugin.
  (Deprecated. prevents Gradle upgrade to the recent version)
- [x] Migrate spoon to composer, see https://github.com/trevjonez/composer-gradle-plugin
  (Causes two gradle deprecation warnings, will stop working. Requires snapshot versions)

**Comment by ligi** [comment]
I think "Migrate spoon to composer" has priority as this would also get rid of the spoon-SNAPSHOT
as for the backend: maybe we can even remove this

**Comment by irgendwr** [comment]
Hey @ligi, seems like you fixed this in your recent commits so I'll close it.
Thanks for your work, let me know if I can be of any help :)

**Comment by ligi** [comment]
Thanks! Yes I finally came around to do this. Thanks for opening the issue!
