### ISSUE TITLE
 enhancement: Windows version compilation

### ISSUE THREAD

**Issue by vvv-easy** [ligi/PassAndroid#237]
Helllo,
Although it seems incredible, there is no FOSS version of passbook viewer for Windows (but not MS Pay).
I know that the passbook can be renamed as a zip file or that I can use an Android simulator with PassAndroid but ... if it's not very difficult, could there be a compilation for windows?
Thank you very much for PassAndroid

**Comment by ligi** [comment]
Thanks for the suggestion - but I rather not touch windows
