### ISSUE TITLE
check zxing 3.2.0

### ISSUE THREAD

**Issue by ligi** [ligi/PassAndroid#25]
is now on maven-central - check if the problem still exists  https://github.com/zxing/zxing/issues/165
if not take the version

**Comment by krt16s** [comment]
Any progress in this? I'd love to have the jar gone, so I can enable auto-updates for fdroid builds :)

**Comment by ligi** [comment]
ack - will look into this soon

**Comment by krt16s** [comment]
I think as of https://github.com/ligi/PassAndroid/commit/89297a2736d74f62c7294e69f882029c99bcf383 this issue can be closed.

**Comment by ligi** [comment]
you are right

**Comment by ligi** [comment]
thanks!
