### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [ligi/PassAndroid#252]
...as `com.android.tools:r8` is not available in any [trusted (by F-Droid) maven repo](https://gitlab.com/fdroid/fdroidserver/blob/master/fdroidserver/scanner.py#L100)

**Comment by simontb** [comment]
Here is the link to the build: https://f-droid.org/wiki/page/org.ligi.passandroid/lastbuild_356

So apparently this is related to #249

**Comment by PanderMusubi** [comment]
The latest successful build for F-Droid is version 3.5.7 on 2020-12-29, which is more than half a year after the reports here above.

Can this issue be closed?

For future (automated) builds for F-Droid, please make tagged releases in https://github.com/ligi/PassAndroid/releases
