### ISSUE TITLE
choose between AsyncTask and IntentService/AsyncTaskLoader

### ISSUE THREAD

**Issue by yulin2** [ligi/PassAndroid#26]
Hello, I'm doing research on Android async programming. I see in `PassAndroid`, you use `IntentService` at some places (`SearchPassesIntentService`) while use `AsyncTask` at other places (such as in `ExtractURLAsIphoneActivity`). I'm wondering how do you choose between `AsyncTask` and `IntentService`? because both are used to execute background tasks.

As far as I know, some articles (for example [this article](http://bon-app-etit.blogspot.com/2013/04/the-dark-side-of-asynctask.html)) mention that AsyncTask leads to memory leak and losing task result when there's a configuration change (such as orientation change). But using `IntentService` or `AsyncTaskLoader` can avoid such problems.

**Comment by ligi** [comment]
It is difficult to boil this down to a few sentences & imho opening an issue for this is not the right way. It always depends on the circumstances:
 SearchPassesIntentService - can be very long running and does not have to be bound to an activity - thats why I use Intentservice there
 ExtractURLAsIphoneActivity - not so long task running in bg ( but network so must be in bg ) - bound to one activity -> so AsyncTask
