### ISSUE TITLE
Sensitive information leakage

### ISSUE THREAD

**Issue by alpha0490** [ligi/PassAndroid#316]
your api keys are leaked here

https://github.com/ligi/PassAndroid/blob/6cdd7ce4f74be54a538014014c426bc647d550b1/android/src/withMaps/AndroidManifest.xml

**Comment by ligi** [comment]
Wondering what exactly is sensitive about the maps API key. What harm can people do having it?

**Comment by ligi** [comment]
I really do not see the point - it needs to be available on the edge - so even if I obfuscate it there - it is in the end deliverable - so no real point in hiding it IMHO.
