### ISSUE TITLE
Previously correct pass is now wrongly displayed after last update

### ISSUE THREAD

**Issue by zedascouves** [ligi/PassAndroid#32]
That's it really...
Android 4.4
![screenshot_2015-06-24-09-47-47](https://cloud.githubusercontent.com/assets/594831/8326076/53e67ea4-1a56-11e5-84f3-fcfd60cef778.png)

**Comment by ligi** [comment]
Do you still have this problem - if so can you send me the pass?

**Comment by zedascouves** [comment]
Hi. I tried again, and it worked, so it may have been a one time thing. I'll close the issue and re-open if it happens again. Cheers.

**Comment by ligi** [comment]
Thanks for the fast reply - forgot to close it when i fixed the issue - it was a problem with the layout-params
