### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by Hauwertlhaufn** [ligi/PassAndroid#33]
A dark theme would be nice, especially when you are on a plane at night. So you don't have to look at a too bright screen.

**Comment by ligi** [comment]
Now with AppCompat DayNight mode this becomes really interesting - unfortunately I would need some graphics assistance for this

**Comment by ligi** [comment]
It is actually not that many graphics - but one the category indicators are needed - perhaps they can be migrated to vector graphics in this process
