### ISSUE TITLE
Android Wear support

### ISSUE THREAD

**Issue by Hauwertlhaufn** [ligi/PassAndroid#34]
Support for Android Wear-watches would be very nice.
So you wouldn't have to pull out your phone, while you have your luggage in your hands.
Example: https://play.google.com/store/apps/details?id=com.delta.mobile.android

**Comment by ViViDboarder** [comment]
An easy way around this feature is to enable support for rich notifications and geofencing or a time based alert. If a pkpass file has GPS coordinates, set up fence around the location, or you can set up a notification to pop up X min before the event starts if it has a time.

That notification can be a rich image notification with the barcode. This will show up on Android Wear automatically.

Of course, a way to navigate them would be great. This is a way to add a new feature for both the phone and the watch at once.

**Comment by ViViDboarder** [comment]
@ligi any advice as to where I should be putting code that requires geofencing? Would that be in `src/withMaps`?

Also, I see you're using Kotlin! Is there any guidline on if that should be used on anything new going forward?

**Comment by ligi** [comment]
yes - it has to get into withMaps when it uses play-services geofencing - it is important that always a fdroid version is buildable when dealing with play-services or other closed source stuff - fdroid gets noMaps flavor.
Regarding kotlin - as there is no lint yet I use it for logic but not close to the android API if possible - might migrate fully when lint for kotlin becomes available
