### ISSUE TITLE
Menu: Change Entry Name

### ISSUE THREAD

**Issue by ax3l** [ligi/PassAndroid#36]
I am using `PassAndroid` version `2.5.5` via F-Droid since a few days and I :heart: it (thank you!).

One nice thing would be, if imported boarding passes could be manually renamed in the menu's listing.

In my case, after clicking and importing the URL in the Turkish Airlines SMS, I got the following two menu entries, which I would like to have renamed myself to something more explicit :)

![passandroid_screenshotmenu](https://cloud.githubusercontent.com/assets/1353258/10669357/130dc3d2-78e9-11e5-8c7e-1b5ce11e0379.png)

**Comment by ligi** [comment]
In v3.0.0 you can edit all passes and also change the description - should be exactly what you wanted

**Comment by ax3l** [comment]
@ligi thank you so much, I updated today and it works like a charm :sparkles:

**Comment by ligi** [comment]
Great! Thanks for the feedback! The UX is still a bit bad in this corner
- but I am in the process of changing this currently.

**Comment by ax3l** [comment]
Awesome, I will follow the progress :rocket:
