### ISSUE TITLE
Wrong time zone in tickets 

### ISSUE THREAD

**Issue by ccamara** [ligi/PassAndroid#360]
After having moved to another country with a different time zone (GMT+1) , all tickets are shown in the phone's original time ZONE (GMT+2), despite the phone has successfully changed to the new time zone and ticket's details show the correct time.

I hope you can fix this issue, which is quite annoying.

On the other hand, thanks for developing this app, which has been working fine for me for years.

**Comment by ligi** [comment]
Are you sure the times in the ticket have a TimeZone attached?

**Comment by ligi** [comment]
without this info I cannot do anything - so closing
