### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by ArnyminerZ** [ligi/PassAndroid#367]
Is this even maintained? Last release is from 2016, issues are not answered, and PRs don't get merged.

What's the current status? Is there a fork or something more updated?

**Comment by ligi** [comment]
It's a bit on the backburner - but the last version is just a bit over a year ago:
![image](https://user-images.githubusercontent.com/111600/156830176-139f59b4-7ee9-4c20-9e44-4f383c19118c.png)
