### ISSUE TITLE
Boarding Pass via AZTEC: PDF417 Alternative

### ISSUE THREAD

**Issue by ax3l** [ligi/PassAndroid#37]
I had an interesting situation in the last days with turkish airlines.

They send out AZTEC based electronic tickets (which are imported fine and work great!) but not all the gates on airports they use can read AZTEC.

So what I thought is: since the AZTEC is *already imported* (and the data within it known) - could one also add a **PDF417 version** of it as an alternative, e.g., while *sliding to the right* in code-full-screen mode?

This would basically imitate a full (printed) boarding pass (that only has PDF417 on it) and is well supported even by scanners at older gates.

Since I got still additionally my boarding passes printed during drop off, I can also give examples of printed boarding passes and electronic versions I got (via private mail).

**Comment by ligi** [comment]
Thanks for your suggestion! Would not have thought that airlines create passes with AZTEC and can not read them then anymore.

Would the following work for you: You can edit passes and change the barcode type there?

**Comment by ax3l** [comment]
Thanks for the suggestion! Yes, that was quite a surprise for me, too.

Editing the QR type would certainly work, too. Just needs to be close to the "full-screen" preview so one can reach it fast in such a case. Seems to me like PDF417 is still a save and always supported fallback.

**Comment by ligi** [comment]
In version 3.0.0 which is now in beta you can edit all passes and also change the barcode format

**Comment by ax3l** [comment]
How cool! Tested it and works great! :sparkles: 

Do you think it might be possible to change the QR code type also via a left-right swipe when it is in zoomed mode?

I am just imagining myself clicking `edit` -> `5x right to barcode` -> `select` -> `save` in front of a queue while boarding :)
