### ISSUE TITLE
Remove unneeded storage permissions

### ISSUE THREAD

**Issue by soshial** [ligi/PassAndroid#372]
When importing a `pkpass` file, no storage permission is actually needed, since the `pkpass` file contents are copied into app private memory anyway.

1. Tested on Android 11 and 12 -- and it imported pkpass file perfectly WITHOUT storage permission:

https://github.com/ligi/PassAndroid/blob/master/android/src/main/java/org/ligi/passandroid/ui/PassImportActivity.kt#L41

<img width="599" alt="Screenshot 2022-06-26 at 19 22 22" src="https://user-images.githubusercontent.com/100644/175823882-08bc4907-5a38-499b-b447-37aeb7284f5c.png">

2. Changing pkpass image could also easily be done without abolute file path: https://github.com/ligi/PassAndroid/blob/master/android/src/main/java/org/ligi/passandroid/ui/edit/ImageEditHelper.kt#L34

Providing an app storage permissions is a dangerous thing and I'd suggest to never do this, when this is so easily avoidable.

**Comment by soshial** [comment]
@ligi

**Comment by spaetz** [comment]
As seen in https://github.com/ligi/PassAndroid/issues/434#issuecomment-1525404259 it turns out that permissions might be necessary in order to read and import passports on Android 13

**Comment by ligi** [comment]
Thanks - but I also need to fix it for Android 13 - as far as I see #460 is the solution.

**Comment by soshial** [comment]
Thank you @ligi, v3.7.3 works perfectly on Android 13. 

Also, I think this option should be removed on Android 13+ (because it won't ever work on recent Android versions):
![Screenshot_20230519_204538_PassAndroid](https://github.com/ligi/PassAndroid/assets/100644/712e8aa2-0e19-4a99-857c-780c01eaac80)
