### ISSUE TITLE
New versions don't make it into the Play Store

### ISSUE THREAD

**Issue by FlorianLoch** [ligi/PassAndroid#378]
Hi there, 
First of all, thanks for developing this app. 

I was just wondering why the latest version on the Play Store is way behind the latest tag in the repository? 

I just downloaded 3.4.7 via the Play Store (dated to 2018), but current tag would be 3.5.7.

But they do make it into the F-Droid store... And even 3.5.7 is from 2020 - and just glancing the commits, there have been some since then ;) 

Any reason for this or did I just miss something? 

Probably similar issue as with #346.

**Comment by ligi** [comment]
I uploaded 3.7.0 to open testing in play store - after testing I will move it to production there.
