### ISSUE TITLE
[Improvement] Safe whitespace around QR code in night mode

### ISSUE THREAD

**Issue by wedebe** [ligi/PassAndroid#380]
For ultimate legibility of codes, there should ideally be a white border around the code when the pass' background is darkened due to Night Mode.

V3.2.2 from GitHub Releases

![screenshot](https://user-images.githubusercontent.com/9741693/215738760-d9c44166-0159-4725-bd8e-cf6e7d5155c2.jpeg)

**Comment by ligi** [comment]
Thanks for the report and sorry for the late reply.
Just checked it - zxing is alreaqdy setting a margin - but not for all types of codes. E.g. aztec has no margin - but e.g. QR has.


![Screenshot_1680241270](https://user-images.githubusercontent.com/111600/229033169-b9b8c365-e03b-4e25-8c25-994e7267078b.png)
![Screenshot_1680241305](https://user-images.githubusercontent.com/111600/229033188-fe7aa5ed-08a7-47bd-a4f3-9a85e6488624.png)
![Screenshot_1680241313](https://user-images.githubusercontent.com/111600/229033211-49252b6c-7381-4290-9ef3-a2b89d954dde.png)
