### ISSUE TITLE
Invalid Passbook when trying to import a PDF

### ISSUE THREAD

**Issue by chipotledonut** [ligi/PassAndroid#431]
I get this error

problem with temp file:java.ioIOExcepction: Stream Closed

**Comment by ligi** [comment]
Can you provide more details like what version of the app you are using? Also can u try another pdf to see if it a problem with a certain PDF (if so it would be good to have this one)

**Comment by jejb** [comment]
I see the same thing on 3.7.0 fdroid Android-10

It seems to be coming from the renovation commit 41821544 ("Modernize").  Everything up to this commit builds and runs just fine on Android-10.  After this everything fails.  I think the problem is the version bumps; they seem to have taken koin to a level that requires at least sdk 31, which is Android-12, so all this could be an artifact of running on
an android version which is now too old.

**Comment by ligi** [comment]
I needed to increase the targetSDK to solve: https://github.com/ligi/PassAndroid/issues/382
but kept the minSDK at 14 - if koin now requires a higher minSDK it should acutally fail the build

**Comment by jejb** [comment]
On Wed, 2023-04-19 at 12:23 -0700, ligi wrote:
> I needed to increase the targetSDK to solve:
> https://github.com/ligi/PassAndroid/issues/382
> but kept the minSDK at 14 - if koin now requires a higher minSDK it
> should acutally fail the build

I understand google is forcing this for app store deployment, which is
likely why everyone is being careless about sdk versions.  I'm trying
to find a version of the Modernize commit that will allow minSdkVersion
to be as low as 29 (at the moment it seems minSdkVersion is somewhere
around 31).  There's definitely something in the Modernize commit that
triggers this Null deref, if I can isolate that, it may be possible to
work backwards and still allow you to compile for 33 for the app store
while still also building for 29.

**Comment by ligi** [comment]
Great - appreciate your support there!
Yea - the new one is still considered a beta-version. Bit sad that f-droid does not really have this concept AFAIK.

**Comment by jejb** [comment]
Now that I have this built, the problem is that the use in the fromContent of InputStreamProvider.kt is getting called prematurely (debug says at the time the fromURI is created).  The fix seems to be to shift the use to where it is actually used for a content based URI, like this

```
diff --git a/android/src/main/java/org/ligi/passandroid/functions/InputStreamProvider.kt b/android/src/main/java/org/ligi/passandroid/functions/InputStreamProvider.kt
index f2e46263..7ff692b8 100644
--- a/android/src/main/java/org/ligi/passandroid/functions/InputStreamProvider.kt
+++ b/android/src/main/java/org/ligi/passandroid/functions/InputStreamProvider.kt
@@ -65,8 +65,6 @@ private fun fromOKHttp(uri: Uri, tracker: Tracker): InputStreamWithSource? {
     return null
 }
 
-private fun fromContent(ctx: Context, uri: Uri) = ctx.contentResolver.openInputStream(uri)?.use {
-    InputStreamWithSource("$uri", it)
-}
+private fun fromContent(ctx: Context, uri: Uri) = InputStreamWithSource("$uri", ctx.contentResolver.openInputStream(uri)!!)
 
 private fun getDefaultInputStreamForUri(uri: Uri) = InputStreamWithSource("$uri", BufferedInputStream(URL("$uri").openStream(), 4096))
diff --git a/android/src/main/java/org/ligi/passandroid/ui/UnzipPassController.kt b/android/src/main/java/org/ligi/passandroid/ui/UnzipPassController.kt
index a0b87040..7afc5afd 100644
--- a/android/src/main/java/org/ligi/passandroid/ui/UnzipPassController.kt
+++ b/android/src/main/java/org/ligi/passandroid/ui/UnzipPassController.kt
@@ -40,10 +40,12 @@ object UnzipPassController : KoinComponent {
 
     fun processInputStream(spec: InputStreamUnzipControllerSpec) {
         try {
-            val tempFile = File.createTempFile("ins", "pass")
-            spec.inputStreamWithSource.inputStream.copyTo(FileOutputStream(tempFile))
-            processFile(FileUnzipControllerSpec(tempFile.absolutePath, spec))
-            tempFile.delete()
+            spec.inputStreamWithSource.inputStream.use {
+                val tempFile = File.createTempFile("ins", "pass")
+                it.copyTo(FileOutputStream(tempFile))
+                processFile(FileUnzipControllerSpec(tempFile.absolutePath, spec))
+                tempFile.delete()
+            }
         } catch (e: Exception) {
             tracker.trackException("problem processing InputStream", e, false)
             spec.failCallback?.fail("problem with temp file: $e")
```
However, I have no idea why this is suddenly a problem when it wasn't previously (or why it only seems to affect androids 10 and 11)

**Comment by chipotledonut** [comment]
Late but 3.7.0 from Fdroid Android 11.

Sorry about that.

**Comment by chipotledonut** [comment]
> Bit sad that f-droid does not really have this concept AFAIK.

They do, the app suggests the last stable release if the last one is mark as alpha AFAIK.

**Comment by ligi** [comment]
> They do, the app suggests the last stable release if the last one is marked as alpha AFAIK.

how to mark as alpha for f-droid?

**Comment by ligi** [comment]
> They do, the app suggests the last stable release if the last one is marked as alpha AFAIK.

how to mark as alpha for f-droid?

**Comment by spaetz** [comment]
Afaik, it is enough to tag the release as X.X-alpha or x.x-beta to mark sth as unstable. Sorry, slightly offtopic in this issue :-)

**Comment by MatthewVernon** [comment]
FWIW, I am seeing this problem when trying to import a .pkpass file, too - I get "Invalid Passbook" problem with temp file: java.io.IOException: Stream Closed
This is passandroid version 3.7.0 from f-droid on an Android 12 device.

If I force install the older version 3.5.7, then the file imports just fine.
