### ISSUE TITLE
Version 3.7.0 from F-Droid can't open any .pkpass file

### ISSUE THREAD

**Issue by vgiralt** [ligi/PassAndroid#444]
I've been using PassAndroid installed from F-Droid for years. All of a sudden it has started refusing to open any .pkpass, even if I try to open one that is already in the application or an .epass from your demo files.

The error is:
`Invalid passbook

problem with temp file:
java.io.IOException: Stream Closed`

The device is a Fairphone 3 running Android 11.

I've tried to install from Google Play but it says the app is compiled from a differente version of Android and refuses to install.

**Comment by tdankert** [comment]
Ran into the same issue on a Xiaomi phone running LineageOS 18.1 (Android 11).
Downgrading the app to 3.5.7 made it usable again.

**Comment by Mister-Teatime** [comment]
Same issue here, and it fails for .pkpass files as well as PDFs -- tried several PDFs, too, which worked on somebody else's phone who has an older version.

...oh, and then F-Droid refused to downgrade because "the package has a lower version string than the one already installed", so I uninstalled and reinstalled the 3.5.7. With the side effect that all my stored and archived tickets are no longer accessible (I had expected it to keep the user data, but apparently that's not how it works)

...that last bit was just a rant, and nobody here is to blame but dammit I'm not happy. If anyone could tell me if/how I could get those tickets back into the app, that would be helpful.

Running LineageOS 19.1 (Android 12), on Xiaomi Pocophone F1

**Comment by jswetzen** [comment]
I've got the same issue. Never used it before, just downloaded and saw there was no way to use it.

**Comment by chipotledonut** [comment]
This issue is talked about in two or three other threads.

[Backups](https://github.com/ligi/PassAndroid/issues/431#issuecomment-1518693984)

If you follow thoae threads or commits pulls, you'll see there's a fix already merged for 3.7.1

**Comment by vgiralt** [comment]
> This issue is talked about in two or three other threads.
> 
> [Backups](https://github.com/ligi/PassAndroid/issues/431#issuecomment-1518693984)

I did search before opening this issue, but nothing appeared. "Backup" does not seem the best subject for an issue abouty the application not doing its thing ;-) :-)
> 
> If you follow thoae threads or commits pulls, you'll see there's a fix already merged for 3.7.1
I've updated to this version, the error does not manifest itself, but trying to import a .pkpass or even a .epass from the demos, result in a screen showing a "Please wait, it will not take long" message.

**Comment by victornoel** [comment]
@vgiralt 3.7.1 was not released as far as I know, so we need to wait for it to get the fix.

Maybe @ligi can tell us when 3.7.1 is expected to be released? Thanks!

**Comment by vgiralt** [comment]
> @vgiralt 3.7.1 was not released as far as I know, so we need to wait for it to get the fix.
> 
> Maybe @ligi can tell us when 3.7.1 is expected to be released? Thanks!

I was sure it was ... F-Droid notified me of a new release and I'm sure it said 3.7.1 but I've rechecked and the installed version was upgrded from 3.5.7, I was to eager to use it :-)

Although, I confirm the behaviour has changed from an error pop-up to a screen with a "wait..." message. Interesting...

**Comment by chipotledonut** [comment]
> I did search before opening this issue, but nothing appeared. "Backup"

There are two or three threads with problems to open pkpass. I just linked about the backups in one of those threads to tell you that I had the same problema as you about backups.

3.7.1 hasn't been released yet.

But whatever, peace out.

**Comment by victornoel** [comment]
Hey @ligi thanks!

I just tested 3.7.1 from f-droid (fairphone 3, android 11), and I can successfully import pkpass files without issue again.

**Comment by soshial** [comment]
"Need permission to import pass" error still persists, though.

**Comment by ligi** [comment]
yes permission problem still exists - tracked here #434

**Comment by vgiralt** [comment]
Once I detected that the permission had "disappeared" (it had been removed by Andrid) after the update to 3.7.1, files are opened quickly.

As the issue reporter I wanted to confirm that it also works for me.

**Comment by andrewshadura** [comment]
@ligi, have you also pushed it out to Google Play?
