### ISSUE TITLE
Won't Start

### ISSUE THREAD

**Issue by ThomasZett** [ligi/PassAndroid#453]
# Creating a issue
 
Current version just will not start at all.
Reinstalled - no change.

S20 with all updates

Thanks for your feedback - this is really important to improve the project!
Please make issues atomar and closeable. This means if you have one idea for an enhancement and experience a bug - please submit 2 issues and don't pack it all in one.
Please try to give a lot of detail - so ideally the issue can be reproduced. At the very minimum it is important to know what version of the app and what version of android you are using and where you got the app from.

**Comment by ligi** [comment]
Please provide some more information.
What version of the app? Installed from where?
Any chance I can get a crashlog?

**Comment by ligi** [comment]
very likely fixed in 3.7.3 - closing - feel free to reopen if you still have a problem
