### ISSUE TITLE
Feature Request: "Add to calender" for tickets

### ISSUE THREAD

**Issue by casperklein** [ligi/PassAndroid#46]
Hi, I noticed, that there is an option to add the time/date of a boarding pass to the phones calender.
The same would be nice for (cinema) tickets.

**Comment by ligi** [comment]
Thanks for the suggestion. But it is not don per pass type at the moment. Every pass gets this option as long as there is a relevantDate field. If this field is missing I do not know how to present a date - So I have to close this.
