### ISSUE TITLE
Stops immediately after the start

### ISSUE THREAD

**Issue by l00ping** [ligi/PassAndroid#55]
Hi,
I have used this app last about a year ago. Now I installed the current version 2.7.0 from F-droid and launched the app to look for enhancements. But the app only opens a white window and then stops. 
I have a Samsung Note 10' Tablet with the old Android 4.1.2
Newly tested: previous version 2.6.4 works correctly.
Regards

**Comment by sniperle** [comment]
Same issue here:

build.board: galbi
build.bootloader: unknown
build.brand: LGE
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: d802
build.display: cm_d802-userdebug 6.0.1 MMB29U 5d1e014c5f test-keys
build.fingerprint: lge/g2_open_com/g2:5.0.2/LRX22G/151061918340a:user/release-keys
build.hardware: g2
build.host: cyanogenmod
build.id: MMB29U
build.manufacturer: lge
build.model: LG-D802
build.product: cm_d802
build.radio: unknown
build.serial: 02a25d8c0f47e3ad
build.tags: test-keys
build.time: 1455877891000
build.type: userdebug
build.user: jenkins
version.codename: REL
version.incremental: 5d1e014c5f
version.release: 6.0.1
version.sdk_int: 23

02-20 10:28:29.894 I/ActivityManager(1023): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.ligi.passandroid/.ui.PassListActivity (has extras)} from uid 10021 on display 0
02-20 10:28:29.942 I/ActivityManager(1023): Start proc 23794:org.ligi.passandroid/u0a107 for activity org.ligi.passandroid/.ui.PassListActivity
02-20 10:28:29.988 W/System  (23794): ClassLoader referenced unknown path: /data/app/org.ligi.passandroid-2/lib/arm
02-20 10:28:29.998 E/JodaTimeAndroid(23794): 	at org.ligi.passandroid.App.onCreate(SourceFile:27)
02-20 10:28:29.999 E/AndroidRuntime(23794): Process: org.ligi.passandroid, PID: 23794
02-20 10:28:29.999 E/AndroidRuntime(23794): java.lang.RuntimeException: Unable to create application org.ligi.passandroid.App: java.lang.RuntimeException: Could not read ZoneInfoMap
02-20 10:28:29.999 E/AndroidRuntime(23794): 	at org.ligi.passandroid.App.onCreate(SourceFile:27)
02-20 10:28:30.000 W/ActivityManager(1023):   Force finishing activity org.ligi.passandroid/.ui.PassListActivity
02-20 10:28:30.522 W/ActivityManager(1023): Activity pause timeout for ActivityRecord{8e6859a u0 org.ligi.passandroid/.ui.PassListActivity t458 f}
02-20 10:28:31.400 I/ActivityManager(1023): Process org.ligi.passandroid (pid 23794) has died

**Comment by marcohald** [comment]
Same here.  Even after removing data and cache

**Comment by locutis-of-borg-1999** [comment]
Great potential, except for the crashing.

**Comment by woj-tek** [comment]
small +1.

reverted to previous version for the time being.

Great app!

**Comment by ligi** [comment]
Sorry for the crash - is fixed with 2.7.1 which should be on fdroid soon

**Comment by locutis-of-borg-1999** [comment]
I just upgraded to v. 2.7.2, and, not only did it operate, but in a quick run, trying a few functions, it didn't crash as it had in the past.

Good stuff!
