### ISSUE TITLE
Some fields in more detail shows as null 

### ISSUE THREAD

**Issue by vrtareg** [ligi/PassAndroid#60]
Hi

I have noticed that in the more section of pass some fields are shown as null. 

First one in screen shoot is full name. 

Regards, 
Areg 
![screenshot_2016-03-17-07-03-27](https://cloud.githubusercontent.com/assets/2562730/13838756/65704b20-ec0e-11e5-9c56-a9962945c36c.png)

**Comment by ligi** [comment]
Thanks! - fixed in 2.8.0
