### ISSUE TITLE
Use the Google Play Referrer link to download a consumer's first pass

### ISSUE THREAD

**Issue by jeroendeleeuw** [ligi/PassAndroid#61]
I think it's a great idea to make it as easy as possible for the consumers that are using the app. Therefor it would be great if can use a link to install the app and directly download the first pass with it. 

The link would look something like this: https://play.google.com/store/apps/details?id=org.ligi.passandroid&refferer=https://walnutapp.com/download/c43af6a4cc0c11e59f1722000a24c03c. Here you can find some [extra information](https://blog.branch.io/technical-guide-to-android-deep-linking-google-play-referrer) on deep linking and how to use it on Android.

I think it would greatly improve the consumer's experience!

**Comment by ligi** [comment]
Who would create such links?

**Comment by friedger** [comment]
The pass providers.

**Comment by ligi** [comment]
;-) I was less interested in the rough direction - I was more wondering about a concrete example ;-)

**Comment by jeroendeleeuw** [comment]
For example a store that wants to offer a solution to install a pass in the Apple Wallet and on a Wallet app on Android. If the consumer wants to install it on Android, he only has to download the app and the pass is automatically added to it.

**Comment by ligi** [comment]
Yea I understood this from the beginning - my problem is a concrete example - like I implement this now - who would actually use it

**Comment by ligi** [comment]
thinking through this a bit deeper right now and stumbled uppon the following

> The link would look something like this: https://play.google.com/store/apps/details?id=org.ligi.passandroid&refferer=https://walnutapp.com/download/c43af6a4cc0c11e59f1722000a24c03c

I think the refferer parameter must be url-encoded

**Comment by ligi** [comment]
Implementing this currently - but is behaving kinda bad if the app is already installed - then the InstallListener is not called

**Comment by ligi** [comment]
v3.1.3 has this feature and is now in beta - also supports the passandroid:// protocol to do the workaround when the app is installed

**Comment by jeroendeleeuw** [comment]
That's really great news! Thank you for this, it makes installing the app a whole lot easier for our users.

**Comment by ligi** [comment]
yea - let's see if it get's some adoption. Unfortunately there was a small bug that I just saw ( really hard to test without uploading to play ) - fixed this wit 3.1.4 which I will upload to beta in some minutes

**Comment by ligi** [comment]
npthe method with using the iframe and custom url described in the blog post you linked is not working on all devices. Will have to get more DataPoints but it seems newer devices forbid this - fails on my Note4 with 5.1.1 - works on a KitKat device - you can also try it out with the latest beta 3.1.5 : 

http://espass.it/auto_install_or_open.html

Passdock seems to use a simmilar approach to the one described in the blog-post you linked - which leads to really bad UX as it is then not able to get to the pass - it always tries to install pass2u on your device as it is not detecting it is already installed ..

**Comment by ligi** [comment]
OK I found a workaround for a reasonable UX on all android devices - a normal intent-filter and a market-redirecting servlet - seems to work everywhere from my first experiments:
this the looks like this: http://pass-cloud.appspot.com/open_or_install?url=http://espass.it/assets/download/pass/movie.espass
Unfortunately then everything has to go through appspot - but the UX is good - Input welcome - will upload 3.1.6 which fully supports this behavior soon to beta

**Comment by ligi** [comment]
I think dynamic links presented at IO 2016 could improve UX in this area: https://www.youtube.com/watch?v=PmaUkTVywD8
