### ISSUE TITLE
Replace the upper left logo with the logo image instead of the icon image

### ISSUE THREAD

**Issue by jeroendeleeuw** [ligi/PassAndroid#62]
It would be great if the upper left logo could actually show the logo image instead of the icon image. Most of the time they will be the same, but we are using multiple passes on the same account so the icon image looks the same for all of our passes.

![passandroid](https://cloud.githubusercontent.com/assets/1493892/14012638/464b5b4c-f1a7-11e5-975f-2602fad3e798.jpg)

**Comment by ligi** [comment]
Problem is the logo is not always square and the icon there has to be square
