### ISSUE TITLE
Bug initializing settings

### ISSUE THREAD

**Issue by Norbert80** [ligi/PassAndroid#63]
Bug 1

When the app is started with a fresh profile automatic increase of display brightness is active. However if you enter the settings "Automatic light" is unchecked.

If you check and then unchecked "Automatic light" and then leave the settings the automatic brightness is inactive.

I would expect that it is intended that this setting is active by default however the checkbox should be checked initially.

Bug 2

"Condensed mode" seems to be always active independent of its checkbox in the settings.

Found with build 2.8.0.

**Comment by ligi** [comment]
thanks - I could reproduce and will fix Bug 1
but I could not reproduce bug 2 - condensed means that the time is at the calendar action and there is one more displayed field this way

**Comment by Norbert80** [comment]
@ligi Thanks for your feedback and explanations. You are right there is no "Bug 2". Sorry.

**Comment by ligi** [comment]
Uploaded 3.0.0 to beta - this bug is fixed there - please join the betatesters and give Feedback!

**Comment by Norbert80** [comment]
@ligi I can confirm that this bug is fixed.

(But I have found another bug: issue #67.)
