### ISSUE TITLE
Message saying that no passbooks are loaded although a passbook is loaded (regression)

### ISSUE THREAD

**Issue by Norbert80** [ligi/PassAndroid#67]
After updating to version 3 (beta subscription active) I found that after the first app start a message is displayed saying that there are no passbooks loaded. However it correctly found the passbook that I have added with an earlier build.

This message has vanished on the second app start.

Please see screenshot below.
![screenshot_2016-04-06-03-44-53](https://cloud.githubusercontent.com/assets/6921696/14406561/9ab3d1e4-feab-11e5-97ed-c0892a948043.png)

Found with build 3.0.1 or 3.0.0. (I'm not sure anymore but I think it was build 3.0.1.)

**Comment by ligi** [comment]
fixed with v3.0.5
