### ISSUE TITLE
EAN-13 / GTIN codes

### ISSUE THREAD

**Issue by sniperle** [ligi/PassAndroid#76]
Great to have 1D barcodes now, thanks. 

I'm missing EAN-13 / GTIN codes that are used on European loyalty cards, like the Payback card or Deutschland card. Would be great if you could add this, thanks.

https://en.m.wikipedia.org/wiki/International_Article_Number_(EAN)

https://en.m.wikipedia.org/wiki/Global_Trade_Item_Number

**Comment by ligi** [comment]
Thanks for the suggestion!

**Comment by ligi** [comment]
so as far as I understood GTIN is encoded in EAN - so if I add EAN-13 we should be good?

**Comment by sniperle** [comment]
Yes, I think EAN-13 coded barcodes will enable your app to cover a lot of loyalty cards.

**Comment by ligi** [comment]
Good to know - I don't use these loyalty cards so I was unaware of this.

**Comment by ligi** [comment]
EAN-13 Support is now in 3.0.9 which I jus uploaded to beta

**Comment by sniperle** [comment]
Thank you very much, will test it soon.

**Comment by sniperle** [comment]
Can you add rotation (like with PDF417) while displaying the big versions of EAN and the other non square barcode please. Thanks :-)

**Comment by ligi** [comment]
You mean in fullscreen?

**Comment by sniperle** [comment]
Yes I think it's full screen, after one touches a barcode.

**Comment by ligi** [comment]
this issue is tracked here - will fix it soon - would be great if you could give feedback if it works for you once the change is released to beta: https://github.com/ligi/PassAndroid/issues/71

**Comment by sniperle** [comment]
Thank you, I'll test and report  :-)

**Comment by ligi** [comment]
is now in beta with 3.1.9

**Comment by sniperle** [comment]
Still waiting for F-Droid ...

**Comment by sniperle** [comment]
F-Droid finally updated to 3.2.0 and it seems to work fine now. Thank you.

**Comment by ligi** [comment]
thanks for reporting and testing!
