### ISSUE TITLE
Add "Date Closest to Farthest" Sort order

### ISSUE THREAD

**Issue by DavisNT** [ligi/PassAndroid#79]
Please add a new `Sort order` named `Date Closest to Farthest` that will sort entries in ascending order by time difference between now and time in passbook.

This sorting order will display most relevant passbooks on top in most cases. 
Unlike `Date Descending` it will not display entries of far future before more relevant ones (entries of closer future or very recent past).

**Comment by ligi** [comment]
That sounds reasonable - will implement it

**Comment by ligi** [comment]
This sort order ( sort by "temporal distance" ) is now in Beta with version 3.1.1 - please let me know if it works for you

**Comment by DavisNT** [comment]
Thanks!

I will test. Can you provide the link for Google Play beta testing
(actually I Googled for it and couldn't find it)?
2016. gada 26. apr. 14:13, "ligi" <notifications@github.com> rakstīja:

**Comment by ligi** [comment]
the link is in the navigation-drawer bottom left

**Comment by DavisNT** [comment]
Thanks for the link!

I have performed some tests of the new version. The "Temporal distance"
sort order seems to be working properly,
but "Date Ascending" actually sorts in DESCENDING order (and vice versa).

I assume that PassSortOrder.getInt() returns incorrect comparator (may be
values of DIRECTION_ASC and DIRECTION_DESC constants should be swapped?)...
2016. gada 26. apr. 15:37, "ligi" <notifications@github.com> rakstīja:

**Comment by ligi** [comment]
Thanks for spotting - will fix this now

**Comment by ligi** [comment]
should be correct in 3.1.2 which is now in beta

**Comment by DavisNT** [comment]
I have tested sorting (Date Ascending, Date Descending and Temporal distance; sorting by Type also seems to work well, but I don't have good test data for it) in 3.1.2 and it is working properly.
