### ISSUE TITLE
pass2u links support

### ISSUE THREAD

**Issue by DavisNT** [ligi/PassAndroid#80]
Looks like there are some websites that use special `pass2u://` (e.g. `pass2u://import/https://www.example.com/passbookfile.pkpass`) links if Android is detected.
An example of such site is [Passdock](http://passdock.com/create-mobile-passes) (I found it when Googling for example passbooks for download). 

I do not know how popular are such websites, but if they are popular may be it is worth to implementing handling these links.

**Comment by ligi** [comment]
Kinda unsure about this - already have so many intent-filters in there and don't really want to support this 3rd party app - perhaps better provide the sites with a better alternative. But when I just tried this site I got a normal passbook link

**Comment by DavisNT** [comment]
I tried the site with Chrome on Android phone (may be you used a different browser or opened the site from PC?). 
Regarding the importance - I really don't know (I think it depends on how popular are these `pass2u://`). :confused:

**Comment by ligi** [comment]
OK could get the link and decide I will do this as it will only be one intent-filter.

**Comment by ligi** [comment]
is included in 3.1.5

**Comment by DavisNT** [comment]
Tested this with 3.1.6. 
Looks like `pass2u://` links are opened in PassAndroid from ordinary HTML, but not from the Passdock site. :confused:

**Comment by ligi** [comment]
Can you please elaborate?

On 15 May 2016 12:32:55 AM GMT+02:00, "Dāvis Mošenkovs" <notifications@github.com> wrote:
>Tested this with 3.1.6. 
>Looks like `pass2u://` links are opened in PassAndroid from ordinary
>HTML, but not from the Passdock site. :confused: 
>
>---
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/ligi/PassAndroid/issues/80#issuecomment-219255284

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by DavisNT** [comment]
I have tested Passdock website with Pass2U installed and it still opens Google Play. 
So looks like that specific website (not PassAndroid handling of `pass2u://` links is malfunctioning.
Sorry for the false heads-up!

**Comment by ligi** [comment]
I did not do extensive testing there - but to me it looks like this iframe trick/hack does not work everywhere - so the fallback ( play-store ) gets active and leads to a really bad UX
