### ISSUE TITLE
Topbar disappears after delete

### ISSUE THREAD

**Issue by knutz86** [ligi/PassAndroid#83]
I have tried this two of the demo passes from the website (only two links work, but that's another bug).
When I delete a pass, the topbar containing the title and menu button disappers and I have to close the app and start it again to get the topbar back. 

App ver.: 3.1.6 (f-droid)

**Comment by ligi** [comment]
Thanks for reporting - when the emptyView is shown you cannot scroll in FAB/AppBar anymore - confirmed - the crux is in MyShyFABBehavior - scrolling FAB and AppBar offscreen should not be possible when the list is empty ( or smaller than the screen )
For the examples I opened https://github.com/esPass/espass.github.io/issues/3

**Comment by ligi** [comment]
This bug is fixed in 3.1.8 which is now in beta - thanks for reporting!
