### ISSUE TITLE
Create pass from scanned QR code

### ISSUE THREAD

**Issue by ockham** [ligi/PassAndroid#85]
It'd be great if PassAndroid allowed me to scan a QR code on my screen to create a corresponding pass.

**Comment by ligi** [comment]
That is already possible - you can create a pass and then add a barcode. then there is a scan options. Please let me know if this does not work for you

**Comment by ockham** [comment]
I think it does, but it is UX wise somewhat confusing to go thru all those fields when adding a new pass via QR code... Couldn't scanning a QR code prefill those other fields?

**Comment by ligi** [comment]
No this is not possible. The QR code only holds the secret-message not informations for the other fields. If you are the provider - you can often correlate the message to the other fields in a database - but I am not the provider. So I will have to close this issue.

**Comment by darix** [comment]
Just wondering e.g. the local cinema seems to have all the informations in the QR code that the apple wallet app can show the picture for the movie and create the pass for the cinema tickets. i can also download the pkpass file from it. but the QR code would make it a bit more comfortable.

**Comment by ligi** [comment]
Can you send me the pass? The barcode should be shown - if not it is a bug with the pass from this provider. Will need to see to fix.

On 16 March 2017 6:53:35 PM GMT+01:00, darix <notifications@github.com> wrote:
>Just wondering e.g. the local cinema seems to have all the informations
>in the QR code that the apple wallet app can show the picture for the
>movie and create the pass for the cinema tickets. i can also download
>the pkpass file from it. but the QR code would make it a bit more
>comfortable.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/ligi/PassAndroid/issues/85#issuecomment-287139664

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ligi** [comment]
Perhaps I also understood your question wrong now seeing the context of the issue. There is for sure no picture in the qr-code. Can you please elaborate a bit?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by darix** [comment]
just used a generic QR code reader to see what is hidden in the QR code from the cinema site: it is the url to the pkpass file.

**Comment by woj-tek** [comment]
OK, a bit of a "feature request" - would it be possible to include "Scan code" in the FAB? I would never figure out that it's possible to create card manually and then from there scan the code...

**Comment by pts** [comment]
Currently when I edit the QR code in PassAndroid and tap the scan code button, the Barcode Reader app starts, correctly scans the QR code, and after a few second I get back to the QR code editor, but without the text being modified. My expectation is: the text in the QR code editor is modified after a successful barcode scanning.
