### ISSUE TITLE
Usage of color information for boardingpasses.

### ISSUE THREAD

**Issue by UmpPCPL** [ligi/PassAndroid#86]
Hi 

I would like to propose to start using color atributes from pass.json.
Example.
  "foregroundColor": "rgb(51, 51, 51)",
  "backgroundColor": "rgb(255, 179, 0)",
  "labelColor": "rgb(102, 102, 102)",

Without this, graphics that include white color are totally invisible.
I am enclosing screenshots of LOT Polish Airlines boarding pass from PassAndroid and application from competition.
Also Lufthansa without correct background ( yellow ) looks worse.

I can send examples of boarding passes directly if it is needed.
 ( I dont want to attach them  here )

Regards and thx for your work.

Michal

======================
![screenshot_2016-06-18-23-55-22](https://cloud.githubusercontent.com/assets/2099681/16176167/0480671c-3607-11e6-9cbf-d6107b4e840d.png)
======================
![screenshot_2016-06-18-23-52-34](https://cloud.githubusercontent.com/assets/2099681/16176168/0484ebac-3607-11e6-92ab-583ffd14b17c.png)

**Comment by ligi** [comment]
Can you send me the passes so I can have a look?

**Comment by UmpPCPL** [comment]
I have sent an email with examples attached. Let me know if you don't receive them.

**Comment by ligi** [comment]
Thanks so much - got them and it looks really helpful - especially  as I met a designer at droidcon who suggested a redesign for flight-passes and having a good set of real passes to test with is really helpful to me.

**Comment by ligi** [comment]
LOT will really look nicer with the bgColor ;-) not yet sure about Lufthansa

![device-2016-06-22-134607](https://cloud.githubusercontent.com/assets/111600/16265467/cc01ae70-387f-11e6-8577-274144094475.png)

I do not want the color behind the text as I have even seen passes with a very similar foreground and background color - then form follows function and I rather have high contrast on the text than a nicer icon.  This is also important fot the upcoming day/night mode

**Comment by UmpPCPL** [comment]
Of course for Lufthansa it doesnt look well.
Just one comment from my side.
Please remember that pkpass format is mainly target towards Iphone users.
It means that testing of pass issuers will be always done at iphone.

In my opinion you should handle color in identical ways us it is hadled by Apple Wallet.
But of course it is up to you ;-)

**Comment by ligi** [comment]
yea - but this is not as trivial as it sounds - perhaps a color contrast
is OK on all iphones - but on some ( cheap ) android phones the contrast
is too low. I do not only write for high-end phones - I also welcome the
lower end ones as I like poor people. Also I am not sure if apple will
do day/night - lot of considerations here. I can't and also do not want
to copy what apple has done. The passbook format has to die in the end -
long live espass ;-)
Also I think I found a solution - I will move the icon into the
indicator on the right - I think this will look good and even give more
space for text then.

**Comment by ligi** [comment]
this would be my suggestion
![device-2016-06-22-145821](https://cloud.githubusercontent.com/assets/111600/16267394/d3019ba4-3889-11e6-992b-784aee791951.png)

**Comment by ligi** [comment]
Implemented it now simmilar to this - balanced the layout a bit more - will release with 3.2.1 as beta

![device-2016-07-18-021920](https://cloud.githubusercontent.com/assets/111600/16904016/349a76c0-4c8e-11e6-8ff2-1b7303d6e4fc.png)
