### ISSUE TITLE
Build environment - short descrition needed

### ISSUE THREAD

**Issue by UmpPCPL** [ligi/PassAndroid#87]
Hi 

I would like to ask somebody to write very short description (wiki page ?)
"how to setup build environment from scratch" .
Just 10 short points not more. Names of software products needed.(?) 

It would like to contribute to development but I don't know how to start.
I promise to improve this wiki page myself afterwords.

Michal

**Comment by ligi** [comment]
This is a pretty standard android application - just import it in android-studio and you are good
