### ISSUE TITLE
Support creation of PDF417 codes

### ISSUE THREAD

**Issue by guerda** [ligi/PassAndroid#88]
Currently you can import PDF417 codes from files, but you cannot create them currently "from scratch".
It would be great if PassAndroid could create new barcodes in this format.

**Comment by ligi** [comment]
This is possible:

![screenshot_20160705-220434](https://cloud.githubusercontent.com/assets/111600/16598114/a76e1b66-42fc-11e6-8f54-6a2b5618ecd4.png)

**Comment by guerda** [comment]
Oh, I must have been blind to oversee that. Thanks, this seems to work for me.
