### ISSUE TITLE
Display word "Boarding pass" 

### ISSUE THREAD

**Issue by mephinet** [ligi/PassAndroid#89]
(yes, this is a bit rediculous)

Today, I was denied to enter the security area of Heraklion Airport when showing my boarding pass with PassAndroid. The security officer, who did not have a barcode scanner but inspected the screen visually, stated that the word "Boarding pass" needs to be shown in the display. Without that, she can't allow access, and I needed to get a paper boarding pass instead.

Now I can't judge if this is a legally, technically correct requirement, but since the change is really simple to be done, I'd propose adding the word "Boarding pass" at the top of the screen.

the view in question: https://cloud.githubusercontent.com/assets/1292953/16545107/0008cfc0-4120-11e6-9dde-b6d8202aad71.png

**Comment by ligi** [comment]
I add this now as a field with the label type at the end of visible fields. This is only added when importing a pass from pkpass format. I think this is a good-enough trade-off .
