### ISSUE TITLE
Improved german translation strings

### ISSUE THREAD

**Issue by Norbert80** [ligi/PassAndroid#90]
All of the following suggestions are applying for pass view mode...

Toast when long-pressing the reload button:
Actual German string: "Aktualisiere"
Suggestion for improved German string: "Aktualisieren"

Toast when long-pressing the garbe can button:
Actual German string: "löschen"
Suggestion for improved German string: "Löschen"

Toast when long-pressing the reload button:
Actual German string: "Aktualisiere"
Suggestion for improved German string: "Aktualisieren"

Menu item Share:
Actual German string: "teilen"
Suggestion for improved German string: "Teilen"

Menu item Edit:
Actual German string: "edit"
Suggestion for improved German string: "Bearbeiten"

(Found with PassAndroid build 3.1.9.)

**Comment by ligi** [comment]
thanks - can you join transifex and the passandroid project there? This is where the strings are managed

**Comment by Norbert80** [comment]
@ligi I have added my suggestions to Transifex. I'm not familiar with Transifex but it looks for me like an reviewer needs to confirm them.

**Comment by ligi** [comment]
thanks! just marked all unreviewed strings in german as reviewed ;-)
