### ISSUE TITLE
Two Categories

### ISSUE THREAD

**Issue by casperklein** [ligi/PassAndroid#97]
Version: 3.2.1

I just added a new pass. Now there are two categories: "New" with all my old passes and "Neu" (german word for "new") with my new added pass.

How can I consolidate the two categories, to have only one with all my passes as before?

**Comment by ligi** [comment]
Did you switch the language in between? You can just move the passes from Neu to New

**Comment by casperklein** [comment]
Thank you for the "moving" tipp. That worked.

I remember, that I changed my phone language from german to english some time ago. But that was just for 1-2 minutes and I haven't started PassAndroid or even added new passes in that time.
