### ISSUE TITLE
Improvement: Show version inside the app

### ISSUE THREAD

**Issue by casperklein** [ligi/PassAndroid#98]
> # Creating a issue
> At the very minimum it is important to know what version of the app

I couln't find the version inside the app which would be the easy way. To find out the version, I had to go through the app manager of my phone.

**Comment by ligi** [comment]
From 3.2.2 onwards you will see it in Help as SubTitle

![device-2016-08-21-210821](https://cloud.githubusercontent.com/assets/111600/17839272/8d34133e-67e3-11e6-8207-b6cbbdafef85.png)
